name: Node.js CI

on:

push:

branches:

main

pull_request:

branches:

main

workflow_dispatch:

schedule:

cron: '0 */6

jobs:

build:

runs-on: ubuntu-latest

strategy:

matrix:

node-version: [20.x]

D

env:

SESSION_ID: PRABATH-MD~AXEXp2yL7eWalRu

GITHUB_AUTH_TOKEN: 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

GITHUB_AUTH_TOKEN

BOT_NUMBER: 94740513917

steps:

name: Checkout repository

uses: actions/checkout@v3

name: Set up Node.js

uses: actions/setup-node@v3

with:

node-version: \${{ matrix.node-

version }}

name: Install dependencies

run: npm install

name: Start application

run: npm start
